/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.programmer3481.s3dlib;

//import org.junit.Test;
//import static org.junit.Assert.*;

public class LibraryTest {
    
}
